# Generated by Django 6.0.1 on 2026-01-12 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(blank=True, default=1, null=True)),
                ('titulo', models.CharField(max_length=300)),
                ('contenido', models.CharField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='media/portadas')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapiens_articulos.categoria')),
                ('tipo_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapiens_articulos.tipo_publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField()),
                ('contenido', models.CharField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapiens_articulos.articulo')),
            ],
        ),
    ]
