# Generated by Django 6.0.1 on 2026-01-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapiens_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('STUDENT', 'Estudiante'), ('PROFESSOR', 'Profesor'), ('MODERATOR', 'Moderador')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Alias',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
