# Generated by Django 6.0.1 on 2026-01-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapiens_users', '0002_user_rol_alter_user_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Contrasenna',
            new_name='Contraseña',
        ),
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='Sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
