# Generated by Django 6.0.1 on 2026-01-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapiens_users', '0003_rename_contrasenna_user_contraseña_user_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Nota',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
